"""initial schema

Revision ID: d4b7571ac78b
Revises: 
Create Date: 2026-05-20 03:23:51.384463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4b7571ac78b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('b_template_html', sa.Text(), nullable=False, comment='Stage 3 에서 추출한 B 문서의 HTML/CSS 템플릿'),
    sa.Column('b_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='B 문서의 필드 구조 스키마 (필드명, 위치, 필수 여부 등)'),
    sa.Column('b_file_url', sa.String(length=500), nullable=True, comment='원본 B 파일의 GCS 저장 URL'),
    sa.Column('b_type', sa.String(length=50), nullable=False, comment='B 파일 형식 : pdf | image'),
    sa.Column('layout_complexity_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Stage 3에서 산출한 레이아웃 복잡도 점수 (렌더러 선택 기준)'),
    sa.Column('preferred_renderer', sa.String(length=20), nullable=False, comment='사용할 렌더러: playwright | weasyprint'),
    sa.Column('font_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='B 분석으로 추정한 유사 Google Fonts 후보 3개'),
    sa.Column('editor_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='비주얼 에디터에서 사용자가 저장한 폰트/레이아웃 수정사항. 다음 변환에 자동 반영'),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Numeric(precision=5, scale=2), nullable=True, comment='이 프로필로 변환 시 평균 신뢰도 점수'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='NULL 이면 영구 보존, 값이 있으면 해당 시각에 자동 삭제'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='적용 대상 스테이지 예 : stage2_extraction, stage5_generation'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='프롬프트 버전 예 : v1.0.0'),
    sa.Column('content', sa.Text(), nullable=False, comment='실제 프롬프트 내용'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='현재 프로덕션에서 사용 중인 버전 여부. 스테이지 당 1개만 True'),
    sa.Column('golden_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Golden Dataset 기준 평균 품질 점수. 이전 버전 대비 2% 이상 저하 시 배포 차단'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='is_active가 True로 변경된 시각'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name', 'version', name='uq_stage_version')
    )
    op.create_table('conversion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('input_file_url', sa.String(length=500), nullable=False, comment='변환할 입력 파일 A의 GCS 저장 URL'),
    sa.Column('input_type', sa.String(length=50), nullable=False, comment='입력 파일 형식 : pdf | image | docx'),
    sa.Column('pixel_similarity_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='최종 출력과 B 원본의 픽셀 유사도 (목표 : 98.00% 이상)'),
    sa.Column('refinement_attempts', sa.Integer(), nullable=False, comment='자동 정제 루프 실행 횟수 (최대 3회)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='queued | processing | waiting_input | completed | failed'),
    sa.Column('current_stage', sa.Integer(), nullable=False, comment='현재 실행 중인 파이프라인 스테이지 번호 (1-7)'),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False, comment='전체 진행률 0.00 - 100.00'),
    sa.Column('result_file_url', sa.String(length=500), nullable=True, comment='생성된 최종 PDF 파일의 GSC 저장 URL'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['conversion_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='연관된 변환 작업 ID. 시스템 이벤트는 NULL'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='이벤트 종류 예: pii_masked, pii_restored, file_deleted, job_failed'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='이벤트 상세 정보. PII 실제 값 포합 금지. 건수/타입만 기록'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False, comment='실행된 스테이지 번호 (1, 1.5는 15로 저장, 2-7)'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='스테이지 이름 예 : stage1_validation, stage5_generation'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='success | failed | retried'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True, comment='스테이지 결과 신뢰도 0.00 - 100.00'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='재시도 횟수. 3회 초과 시 사용자 개입 요청'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='호출한 Gemini 모델명 예 : gemini-1.5-pro'),
    sa.Column('prompt_version', sa.String(length=50), nullable=True, comment='사용된 프롬프트 버전 예: v1.0.0. LLMOps 회귀 추적에 활용'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Gemini API 입력 토큰 수'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Gemini API 출력 토큰 수'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True, comment='이 스테이지에서 소모된 API 비용 (달러)'),
    sa.Column('hallucination_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Self-RAG 검증 결과. {sentence, grounded, soruce} 목록'),
    sa.Column('grounding_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='원문 근거 보존율. 80% 미만 시 사용자 경고'),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='이 스테이지의 입력 요약 (디버깅 및 재시도 참고용)'),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='이 스테이지의 산출물'),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='실패 시 에러 상세 정보'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='스테이지 실행 시간 (밀리초)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_results')
    op.drop_table('audit_logs')
    op.drop_table('conversion_jobs')
    op.drop_table('prompt_versions')
    op.drop_table('conversion_profiles')
    # ### end Alembic commands ###
